# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VodafonePhotos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VodafonePhotos

    pod 'Alamofire'
  	pod 'SwiftyJSON'
  	pod 'SDWebImage'
    pod 'Toast-Swift'
    
  target 'VodafonePhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VodafonePhotosUITests' do
    # Pods for testing
  end

end
